language: rust
rust:
  - stable
  - beta
  - nightly
services:
  - docker
before_install:
  - docker build -t pinger-test .
matrix:
  allow_failures:
    - rust: nightly
script:
  - docker run --rm pinger-test
